name: WorldSelectorH
version: 1.3.3
main: fr.formiko.worldselectorh.WorldSelectorHPlugin
description: Select part of the world.
author: Hydrolien
website: https://github.com/HydrolienF/WorldSelectorH
api-version: '1.20'
commands:
   select:
      description: Select part of the world.
      usage: /select <x1> <z1> <x2> <z2> (<world>)
      permission: worldselectorh.select