name: $name
version: "$version"
main: $group.${name}Plugin
description: "$description"
author: Hydrolien
website: https://github.com/HydrolienF/WorldSelectorH
api-version: $apiVersion
folia-supported: true
commands:
   select:
      description: Select part of the world.
      usage: /select <x1> <z1> <x2> <z2> (<world>)
      permission: worldselectorh.select